# Generated by Django 4.1.1 on 2022-09-30 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("flight", "0002_alter_reservation_flight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="flight",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="flight.flight"
            ),
        ),
    ]
